### ISSUE TITLE
Incorrect usage instructions in `PACKAGE-README.md`

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/pstld#2]
The `PACKAGE-README.md` file has the following suggestion:

```
depends: libpstld ^0.1.0 ? ($build.host.class == 'macos')
```

The use of `build.host.class` is incorrect since it assumes that host is the same as target (basically the assumption that is responsible for the majority of broken cross-compilation setups). The correct way would be to use the `cxx.target.class` variable.

**Comment by helmesjo** [comment]
Fixed in (published) `0.1.0+4`.
